version: '2'

services:
  nodejs:
    image: js/node
    build:
      context: ../node/
      args:
        USER: ${ENV_USER}
        GID: ${ENV_GID}
        UID: ${ENV_UID}
  mysql:
    image: lucydb
    build:
      context: ../lucydb/
